export const styles = {
  container: {
    display: "flex",
    height: "100vh",
  },
  mapContainer: {
    flex: "1",
    position: "relative",
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  loadingSpinner: {
    border: "4px solid #f3f3f3",
    borderTop: "4px solid #3498db",
    borderRadius: "50%",
    width: "40px",
    height: "40px",
    animation: "spin 1s linear infinite",
  },
  loadingText: {
    color: "white",
    marginTop: "10px",
  },
  top: {
    position: "absolute",
    width: "35%",
    top: "20px",
    left: "35%",
    paddingLeft: "10px",
    backgroundColor: "rgba(0,0,0,0.7)",
    padding: "10px",
    borderRadius: "10px",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    zIndex: 10,
  },
  area: {
    marginLeft: 40,
    color: "white",
  },
  perimeter: {
    color: "white",
    marginRight: 45,
  },
  controls: {
    position: "absolute",
    bottom: "30px",
    right: "70px",
    display: "flex",
    backgroundColor: "rgba(0,0,0,0.5)",
    height: "70px",
    width: "350px",
    borderRadius: "10px",
    paddingLeft: "40px",
    alignItems: "center",
    justifyContent: "center",
  },
  controlBtn: {
    padding: "5px 20px",
    marginRight: "40px",
  },
  mapControls: {
    position: "absolute",
    top: "10px",
    left: "10px",
    zindex: "5",
    background: "white",
    padding: "10px",
    borderRadius: "5px",
    boxShadow: "0 2px 6px rgba(0, 0, 0, 0.3)",
    display: "flex",
    alignItems: "center",
  },
};
