export const styles = {
  container: {
    display: "flex",
    height: "100vh",
  },
  mapContainer: {
    flex: "1",
    position: "relative",
  },
  top: {
    position: "absolute",
    width: "35%",
    top: "20px",
    left: "35%",
    paddingLeft: "10px",
    backgroundColor: "rgba(0,0,0,0.7)",
    padding: "10px",
    borderRadius: "10px",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    zIndex: 10,
  },
  area: {
    marginLeft: 40,
    color: "white",
  },
  perimeter: {
    color: "white",
    marginRight: 45,
  },
  controls: {
    position: "absolute",
    bottom: "20px",
    right: "30px",
    display: "flex",
    gap: "10px",
  },
  controlBtn: {
    padding: "5px 20px",
    backgroundColor: "#007BFF",
    color: "white",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    marginRight: "40px",
  },
  controlBtnCancel: {
    backgroundColor: "#DC3545",
  },
  mapControls: {
    position: "absolute",
    top: "10px",
    left: "10px",
    zindex: "5",
    background: "white",
    padding: "10px",
    borderRadius: "5px",
    boxShadow: "0 2px 6px rgba(0, 0, 0, 0.3)",
    display: "flex",
    alignItems: "center",
  },
};
