import { BsJustifyLeft } from "react-icons/bs";

export const styles = {
  backButton: {
    marginLeft: "10px",
    cursor: "pointer",
    color: "white",
  },

  content: {
    paddingLeft: "1px",
    paddingRight: "1px",
    width: "100%",
    marginTop: "0px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "whitesmoke",
  },
  header: {
    display: "flex",
    width: "100%",
    height: "45px",
    backgroundColor: "#007BFF",
    alignItems: "center",
  },

  titleText1: {
    fontSize: 15,
    fontWeight: "bold",
    marginBottom: 0,
    color: "white",
    marginLeft: "95px",
  },
  Box1: {
    width: "90%",
    height: "81px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "white",
    marginTop: "10px",
    borderRadius: "11px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
    padding: "8px",
  },
  titleText: {
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 0,
  },
  propertyBox: {
    display: "flex",
    flexDirection: "coloumn",
    alignItems: "center",
    justifyContent: "center",
    height: 50,
    width: "100%",
    backgroundColor: "white",
  },

  property: {
    display: "flex",
    flexDirection: "row",
    height: "100%",
    alignItems: "center",
    justifyContent: "left",
    backgroundColor: "white",
    width: "46%",
    //height: 50,
  },

  propertyDetails: {
    flexDirection: "column",
    marginLeft: 10,
    width: "50%",
    //height: 40,
    backgroundColor: "white",
  },

  propertyLabel: {
    fontSize: 12,
    marginBottom: 0,
  },

  propertyValue: {
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 0,
  },
  box2: {
    display: "flex",
    width: "95%",
    height: 65,
    flexDirection: "column",
    backgroundColor: "white",
    marginTop: 10,
    borderRadius: 11,
    padding: 0,
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  box2InnerTop: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "white",
    width: "86%",
    paddingLeft: 10,
    marginTop: 4,
  },

  box2PropertyDetails: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginLeft: 5,
    width: "80%",
    backgroundColor: "white",
  },
  Box2PropertyLabel: {
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 0,
  },
  BoxPropertyLabel:{
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 0,
    marginRight: 180,
  },
  box2InnerBottom: {
    display: "flex",
    justifyContent: "space-between",
    paddingLeft: 15,
    paddingRight: 15,
    marginTop: -4,
    backgroundColor: "white",
  },
  box2Button: {
    borderColor: "#CED0D4",
    borderWidth: 1,
    borderRadius: 5,
    border: "1px solid #CED0D4",
    backgroundColor: "#fff",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    width: 70,
  },
  box2ButtonText: {
    color: "grey",
    fontSize: 13,
    marginBottom: 0,
  },

  box3: {
    display: "flex",
    width: "95%",
    // height: 70,
    flexDirection: "column",
    backgroundColor: "white",
    marginTop: 10,
    borderRadius: 11,
    padding: 0,
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
    height: "auto",
  },
  box3InnerBottom: {
    display: "flex",
    justifyContent: "space-between",
    paddingLeft: 15,
    paddingRight: 15,
    marginTop: 3,
  },
  dropDownContainer: {
    display: "flex",
    alignItems: "center",
    marginRight: 35,
  },
  dropDown2Container:{
    display: "flex",
    alignItems: "center",
    marginRight: 35,
    width: 200,
    borderRadius: 50,
    marginLeft: 35,
    marginTop: 10,
    padding: -10,
    borderColor: "grey",
  },
  dropdown: {
    width: 70,
    backgroundColor: "white",
    borderRadius: 5,
    borderColor: "#CED0D4",
    borderWidth: 1,
    border: "1px solid #CED0D4",
    fontSize: 12,
  },
  dropdown2:{
    width: 200,
    backgroundColor: "white",
    borderRadius: 5,
    borderColor: "#CED0D4",
    borderWidth: 1,
    border: "1px solid #CED0D4",
    fontSize: 12,
  },
  box3inputContainer: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    height: "65%",
    paddingRight: -10,
  },
  box3input: {
    display: "flex",
    backgroundColor: "white",
    width: "45%",
    borderBottomWidth: 1,
    borderBottomColor: "lightgray",
    justifyContent: "center",
    alignItems: "center",
    borderBottom: "1px solid gray",
    borderLeft: "none",
    borderRight: "none",
    borderTop: "none",
    outline: "none",
    fontSize: 14,
  },
  box3inputLabel: {
    fontSize: 12,
    marginBottom: 0,
  },
  box3middleContainer: {
    display: "flex",
    flex: 1,
    flexDirection: "row",
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
  },
  addButtonContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  addButton: {
    display: "flex",
    width: 50,
    height: 20,
    backgroundColor: "#0866FF",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 7,
    borderRadius: 7,
    borderWidth: 0,
  },

  addButtonText: {
    color: "white",
    fontSize: 12,
    marginBottom: 0,
  },
  box5: {
    display: "flex",
    width: "95%",
    height: 35,
    flexDirection: "row",
    // justifyContent: "space-between",
    backgroundColor: "white",
    marginTop: 10,
    borderRadius: 11,
    padding: 0,
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  // box5inputContainer: {
  //   marginLeft: -500,
  //   // backgroundColor:"red",
  // },
  box5leftcontainer: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "white",
    paddingLeft: 10,
    paddingRight: 0,
    marginRight: 0,
    marginTop: 7,
    marginBottom: 7,
    width: "30%",
  },
  box5inputContainer: {
    marginTop: 8,
    height: "50%",
  },
  box7: {
    display: "flex",
    width: "95%",
    height: "auto",
    flexDirection: "column",
    backgroundColor: "white",
    marginTop: 10,
    borderRadius: 11,
    padding: 0,
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  box7InputContainer: {
    display: "flex",
    flexDirection: "row",
    // backgroundColor: "green",
    alignItems: "center",
    // justifyContent: "space-between",
    width: "100%",
    height: "30%",
    marginTop: 20,
    marginLeft: 20,
    marginRight: 20,
  },
  box7inputLabel: {
    fontSize: 12,
    marginBottom: 0,
    width: "20%",
    marginLeft: 10,
  },
  box7input: {
    display: "flex",
    backgroundColor: "white",
    width: "52%",
    borderBottomWidth: 1,
    borderBottomColor: "lightgray",
    justifyContent: "center",
    alignItems: "center",
    borderBottom: "1px solid gray",
    borderLeft: "none",
    borderRight: "none",
    borderTop: "none",
    outline: "none",
    height: 20,
    marginLeft: -5,
    fontSize: 14,
  },
  box7addButtonContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-middle",
    marginTop: 15,
    marginBottom: 15,
    marginRight: 100,
    marginLeft: 80,
    height: 15,
  },
  bottom: {
    width: "92%",
    alignItems: "center",
    marginTop: 10,
  },

  Button1: {
    display: "flex",
    width: "100%",
    height: 30,
    backgroundColor: "#0866FF",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    borderRadius: 11,
    borderWidth: 0,
  },
  pressedButton: {
    borderColor: "#0866FF",
    borderWidth: 1,
    borderRadius: 5,
    border: "1px solid #CED0D4",
    backgroundColor: "#fff",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    width: 70,
  },
  pressedText: {
    color: "#0866FF",
    fontSize: 13,
    marginBottom: 0,
  },
  displayValuesContainer: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 8,
    alignItems: "center",
    backgroundColor: "white",
    height: "max-content",
    borderRadius: 11,
    width: "auto",
  },
  displayValueContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: "white",
    marginRight: 10,
    marginLeft: 10,
    marginBottom: 10,
    borderRadius: 8,
    padding: 2,
    width: "auto",
    height: 30,
    border: "1px solid lightblue",
  },
  displayValueText: {
    fontSize: 10,
    marginRight: 5,
    color: "#007BFF",
  },
  closeButton: {
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    padding: 0,
  },
  closeButtonText: {
    color: "white",
    fontSize: 14,
  },
  searchbar: {
    width: 200,
    borderRadius: 50,
    marginLeft: 35,
    marginTop: 10,
    padding: -10,
    borderColor: "grey",
  },
  searchbarList: {
    width: 200,
    borderRadius: 11,
    marginLeft: 35,
    marginTop: -1, //To align the dropdown with the search box
  },
  searchbarListItems: {
    cursor: "pointer",
    padding: "5px 20px",
    borderRadius: 11,
  },
};
