version: "3.8"
services:
  frontend:
    image: fieldmaster.azurecr.io/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
  backend:
    image: fieldmaster.azurecr.io/backend:latest
    container_name: backend
    ports:
      - "5000:5000"
